apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: backend
          image: srikanthsai/zomato_new:0436748936d87c8d775163a1eeb1f8ba0d1d548e

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
